version: "1.0.3"
services:
  db:
    image: mysql:8.0.34
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      # ping if mysql server accept connections
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer:4.8.1 
    restart: always
    ports:
      - 8080:8080

  api:
    depends_on:
      db:
        condition: service_healthy
    build: ./
    restart: on-failure
    environment:
      - DB_HOST=db
      - DB_USER_NAME=$MYSQLDB_USER
      - DB_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - DB_NAME=${MYSQLDB_DATABASE}
      - DB_PORT=${MYSQLDB_DOCKER_PORT}
    ports:
      - ${API_LOCAL_PORT}:${API_DOCKER_PORT}
    command: ['sh', './docker/start-api.sh']

volumes:
  db-data:


